#!/bin/bash

while true; do
    RES=$(./philo 5 800 200 200 7  |tee result.txt | grep "is eating" | wc -l)

    if [ "$RES" -lt 35 ] ; then
        echo "ERROR : found "$RES" 'is eating'"
        break
    fi
	echo "Found "$RES" 'is eating'"
    sleep 2
done
